# ETL
(Extract, Transform, Load)

#### Importamos las librerias a utlizar

In [1]:
import io
import pandas as pd
import numpy as np
import re 
import pyarrow.parquet as pq
import sys

### Extraccion de datos

#### Cargamos los archivos .csv

In [2]:
#Descargar el dataset movies_dataset.csv almacenado en drive
!gdown https://drive.google.com/file/d/14TgaTAdgVGgK_OBo6kMrGpPhMQ95wRLZ/view?usp=drive_link --fuzzy

Downloading...
From: https://drive.google.com/uc?id=14TgaTAdgVGgK_OBo6kMrGpPhMQ95wRLZ
To: d:\HENRY\ProyectoIndividual_1\PROYECTO_INDIVIDUAL\movies_dataset.csv

  0%|          | 0.00/34.4M [00:00<?, ?B/s]
  2%|▏         | 524k/34.4M [00:00<00:15, 2.12MB/s]
  3%|▎         | 1.05M/34.4M [00:00<00:14, 2.38MB/s]
  5%|▍         | 1.57M/34.4M [00:00<00:12, 2.54MB/s]
  6%|▌         | 2.10M/34.4M [00:00<00:11, 2.72MB/s]
  8%|▊         | 2.62M/34.4M [00:01<00:11, 2.70MB/s]
  9%|▉         | 3.15M/34.4M [00:01<00:12, 2.60MB/s]
 11%|█         | 3.67M/34.4M [00:01<00:11, 2.66MB/s]
 12%|█▏        | 4.19M/34.4M [00:01<00:11, 2.69MB/s]
 14%|█▎        | 4.72M/34.4M [00:01<00:10, 2.88MB/s]
 15%|█▌        | 5.24M/34.4M [00:01<00:10, 2.87MB/s]
 17%|█▋        | 5.77M/34.4M [00:02<00:10, 2.82MB/s]
 18%|█▊        | 6.29M/34.4M [00:02<00:09, 3.05MB/s]
 20%|█▉        | 6.82M/34.4M [00:02<00:08, 3.10MB/s]
 21%|██▏       | 7.34M/34.4M [00:02<00:08, 3.22MB/s]
 23%|██▎       | 7.86M/34.4M [00:02<00:08, 3.25MB/s]
 24%|██▍       | 8.39M/34.4M [00:02<00:08, 3.17MB/s]
 26%|██▌       | 8.91M/34.4M [00:03<00:07, 3.24MB/s]
 27%|██▋       | 9.44M/34.4M [00:03<00:07, 3.34MB/s]
 29%|██▉       | 9.96M/34.4M [00:03<00:07, 3.19MB/s]
 30%|███       | 10.5M/34.4M [00:03<00:07, 3.35MB/s]
 32%|███▏      | 11.0M/34.4M [00:03<00:06, 3.40MB/s]
 33%|███▎      | 11.5M/34.4M [00:03<00:06, 3.45MB/s]
 35%|███▌      | 12.1M/34.4M [00:04<00:06, 3.20MB/s]
 37%|███▋      | 12.6M/34.4M [00:04<00:06, 3.18MB/s]
 38%|███▊      | 13.1M/34.4M [00:04<00:06, 3.30MB/s]
 40%|███▉      | 13.6M/34.4M [00:04<00:06, 3.26MB/s]
 41%|████      | 14.2M/34.4M [00:04<00:06, 3.25MB/s]
 43%|████▎     | 14.7M/34.4M [00:04<00:06, 3.11MB/s]
 44%|████▍     | 15.2M/34.4M [00:05<00:06, 3.19MB/s]
 46%|████▌     | 15.7M/34.4M [00:05<00:05, 3.28MB/s]
 47%|████▋     | 16.3M/34.4M [00:05<00:05, 3.27MB/s]
 49%|████▊     | 16.8M/34.4M [00:05<00:05, 3.52MB/s]
 50%|█████     | 17.3M/34.4M [00:05<00:06, 2.67MB/s]
 52%|█████▏    | 17.8M/34.4M [00:05<00:05, 2.95MB/s]
 53%|█████▎    | 18.4M/34.4M [00:06<00:05, 3.19MB/s]
 55%|█████▍    | 18.9M/34.4M [00:06<00:04, 3.19MB/s]
 56%|█████▋    | 19.4M/34.4M [00:06<00:04, 3.19MB/s]
 58%|█████▊    | 19.9M/34.4M [00:06<00:04, 3.37MB/s]
 59%|█████▉    | 20.4M/34.4M [00:06<00:04, 3.31MB/s]
 61%|██████    | 21.0M/34.4M [00:06<00:03, 3.44MB/s]
 62%|██████▏   | 21.5M/34.4M [00:06<00:03, 3.59MB/s]
 64%|██████▍   | 22.0M/34.4M [00:07<00:03, 3.64MB/s]
 65%|██████▌   | 22.5M/34.4M [00:07<00:03, 3.74MB/s]
 67%|██████▋   | 23.1M/34.4M [00:07<00:03, 3.65MB/s]
 68%|██████▊   | 23.6M/34.4M [00:07<00:02, 3.70MB/s]
 70%|███████   | 24.1M/34.4M [00:07<00:02, 3.58MB/s]
 72%|███████▏  | 24.6M/34.4M [00:07<00:02, 3.64MB/s]
 73%|███████▎  | 25.2M/34.4M [00:07<00:02, 3.77MB/s]
 75%|███████▍  | 25.7M/34.4M [00:08<00:02, 3.74MB/s]
 76%|███████▌  | 26.2M/34.4M [00:08<00:02, 3.69MB/s]
 78%|███████▊  | 26.7M/34.4M [00:08<00:02, 3.82MB/s]
 79%|███████▉  | 27.3M/34.4M [00:08<00:01, 3.69MB/s]
 81%|████████  | 27.8M/34.4M [00:08<00:01, 3.77MB/s]
 82%|████████▏ | 28.3M/34.4M [00:08<00:01, 3.80MB/s]
 84%|████████▎ | 28.8M/34.4M [00:08<00:01, 3.54MB/s]
 85%|████████▌ | 29.4M/34.4M [00:09<00:01, 3.44MB/s]
 87%|████████▋ | 29.9M/34.4M [00:09<00:01, 3.47MB/s]
 88%|████████▊ | 30.4M/34.4M [00:09<00:01, 3.47MB/s]
 90%|████████▉ | 30.9M/34.4M [00:09<00:01, 3.40MB/s]
 91%|█████████▏| 31.5M/34.4M [00:09<00:00, 3.27MB/s]
 93%|█████████▎| 32.0M/34.4M [00:09<00:00, 3.47MB/s]
 94%|█████████▍| 32.5M/34.4M [00:09<00:00, 3.44MB/s]
 96%|█████████▌| 33.0M/34.4M [00:10<00:00, 3.31MB/s]
 97%|█████████▋| 33.6M/34.4M [00:10<00:00, 3.33MB/s]
 99%|█████████▉| 34.1M/34.4M [00:10<00:00, 3.31MB/s]
100%|██████████| 34.4M/34.4M [00:10<00:00, 3.26MB/s]

In [3]:
#Descargar el dataset credits.csv almacenado en drive
!gdown https://drive.google.com/file/d/1LeTw5KXPdRiy9CIf9yCj-qx5MsAwQ0cB/view?usp=sharing --fuzzy

Downloading...
From (original): https://drive.google.com/uc?id=1LeTw5KXPdRiy9CIf9yCj-qx5MsAwQ0cB
From (redirected): https://drive.google.com/uc?id=1LeTw5KXPdRiy9CIf9yCj-qx5MsAwQ0cB&confirm=t&uuid=6add5d62-489e-4649-9850-b0b1c7e0e2d0
To: d:\HENRY\ProyectoIndividual_1\PROYECTO_INDIVIDUAL\credits.csv

  0%|          | 0.00/190M [00:00<?, ?B/s]
  0%|          | 524k/190M [00:00<01:40, 1.89MB/s]
  1%|          | 1.05M/190M [00:00<01:33, 2.02MB/s]
  1%|          | 1.57M/190M [00:00<01:29, 2.10MB/s]
  1%|          | 2.10M/190M [00:00<01:22, 2.27MB/s]
  1%|▏         | 2.62M/190M [00:01<01:24, 2.22MB/s]
  2%|▏         | 3.15M/190M [00:01<01:17, 2.40MB/s]
  2%|▏         | 3.67M/190M [00:01<01:11, 2.60MB/s]
  2%|▏         | 4.19M/190M [00:01<01:06, 2.78MB/s]
  2%|▏         | 4.72M/190M [00:01<01:07, 2.74MB/s]
  3%|▎         | 5.24M/190M [00:02<01:06, 2.79MB/s]
  3%|▎         | 5.77M/190M [00:02<01:02, 2.96MB/s]
  3%|▎         | 6.29M/190M [00:02<01:00, 3.03MB/s]
  4%|▎         | 6.82M/190M [00:02<00:59, 3.08MB/s]
  4%|▍         | 7.34M/190M [00:02<00:59, 3.08MB/s]
  4%|▍         | 7.86M/190M [00:02<01:02, 2.93MB/s]
  4%|▍         | 8.39M/190M [00:03<00:58, 3.09MB/s]
  5%|▍         | 8.91M/190M [00:03<00:56, 3.23MB/s]
  5%|▍         | 9.44M/190M [00:03<00:52, 3.45MB/s]
  5%|▌         | 9.96M/190M [00:03<00:52, 3.46MB/s]
  6%|▌         | 10.5M/190M [00:03<00:50, 3.57MB/s]
  6%|▌         | 11.0M/190M [00:03<00:53, 3.36MB/s]
  6%|▌         | 11.5M/190M [00:03<00:50, 3.51MB/s]
  6%|▋         | 12.1M/190M [00:04<00:52, 3.38MB/s]
  7%|▋         | 12.6M/190M [00:04<00:49, 3.56MB/s]
  7%|▋         | 13.1M/190M [00:04<00:48, 3.64MB/s]
  7%|▋         | 13.6M/190M [00:04<00:48, 3.65MB/s]
  7%|▋         | 14.2M/190M [00:04<00:48, 3.64MB/s]
  8%|▊         | 14.7M/190M [00:04<00:47, 3.68MB/s]
  8%|▊         | 15.2M/190M [00:05<00:52, 3.34MB/s]
  8%|▊         | 15.7M/190M [00:05<00:57, 3.05MB/s]
  9%|▊         | 16.3M/190M [00:05<01:08, 2.55MB/s]
  9%|▉         | 16.8M/190M [00:05<01:06, 2.61MB/s]
  9%|▉         | 17.3M/190M [00:05<01:06, 2.61MB/s]
  9%|▉         | 17.8M/190M [00:06<01:01, 2.80MB/s]
 10%|▉         | 18.4M/190M [00:06<01:00, 2.83MB/s]
 10%|▉         | 18.9M/190M [00:06<01:00, 2.84MB/s]
 10%|█         | 19.4M/190M [00:06<00:55, 3.08MB/s]
 10%|█         | 19.9M/190M [00:06<00:54, 3.11MB/s]
 11%|█         | 20.4M/190M [00:06<00:55, 3.08MB/s]
 11%|█         | 21.0M/190M [00:07<00:52, 3.20MB/s]
 11%|█▏        | 21.5M/190M [00:07<00:51, 3.24MB/s]
 12%|█▏        | 22.0M/190M [00:07<00:48, 3.44MB/s]
 12%|█▏        | 22.5M/190M [00:07<00:50, 3.28MB/s]
 12%|█▏        | 23.1M/190M [00:07<00:47, 3.50MB/s]
 12%|█▏        | 23.6M/190M [00:07<00:47, 3.49MB/s]
 13%|█▎        | 24.1M/190M [00:07<00:47, 3.52MB/s]
 13%|█▎        | 24.6M/190M [00:08<00:47, 3.50MB/s]
 13%|█▎        | 25.2M/190M [00:08<00:45, 3.66MB/s]
 14%|█▎        | 25.7M/190M [00:08<00:46, 3.51MB/s]
 14%|█▍        | 26.2M/190M [00:08<00:44, 3.71MB/s]
 14%|█▍        | 26.7M/190M [00:08<00:42, 3.82MB/s]
 14%|█▍        | 27.3M/190M [00:08<00:43, 3.77MB/s]
 15%|█▍        | 27.8M/190M [00:08<00:44, 3.66MB/s]
 15%|█▍        | 28.3M/190M [00:09<00:43, 3.69MB/s]
 15%|█▌        | 28.8M/190M [00:09<00:42, 3.81MB/s]
 15%|█▌        | 29.4M/190M [00:09<00:41, 3.86MB/s]
 16%|█▌        | 29.9M/190M [00:09<00:43, 3.71MB/s]
 16%|█▌        | 30.4M/190M [00:09<00:43, 3.67MB/s]
 16%|█▋        | 30.9M/190M [00:09<00:42, 3.70MB/s]
 17%|█▋        | 31.5M/190M [00:09<00:46, 3.39MB/s]
 17%|█▋        | 32.0M/190M [00:10<00:44, 3.51MB/s]
 17%|█▋        | 32.5M/190M [00:10<00:44, 3.51MB/s]
 17%|█▋        | 33.0M/190M [00:10<00:43, 3.64MB/s]
 18%|█▊        | 33.6M/190M [00:10<00:53, 2.94MB/s]
 18%|█▊        | 34.1M/190M [00:10<00:50, 3.11MB/s]
 18%|█▊        | 34.6M/190M [00:10<00:49, 3.15MB/s]
 18%|█▊        | 35.1M/190M [00:11<00:46, 3.33MB/s]
 19%|█▉        | 35.7M/190M [00:11<00:46, 3.33MB/s]
 19%|█▉        | 36.2M/190M [00:11<00:43, 3.51MB/s]
 19%|█▉        | 36.7M/190M [00:11<00:44, 3.44MB/s]
 20%|█▉        | 37.2M/190M [00:11<00:42, 3.56MB/s]
 20%|█▉        | 37.7M/190M [00:11<00:48, 3.15MB/s]
 20%|██        | 38.3M/190M [00:12<00:48, 3.11MB/s]
 20%|██        | 38.8M/190M [00:12<00:46, 3.25MB/s]
 21%|██        | 39.3M/190M [00:12<00:44, 3.35MB/s]
 21%|██        | 39.8M/190M [00:12<00:45, 3.33MB/s]
 21%|██▏       | 40.4M/190M [00:12<00:42, 3.50MB/s]
 22%|██▏       | 40.9M/190M [00:12<00:42, 3.51MB/s]
 22%|██▏       | 41.4M/190M [00:12<00:45, 3.27MB/s]
 22%|██▏       | 41.9M/190M [00:13<00:42, 3.51MB/s]
 22%|██▏       | 42.5M/190M [00:13<00:41, 3.52MB/s]
 23%|██▎       | 43.0M/190M [00:13<00:43, 3.38MB/s]
 23%|██▎       | 43.5M/190M [00:13<00:46, 3.15MB/s]
 23%|██▎       | 44.0M/190M [00:13<00:43, 3.35MB/s]
 23%|██▎       | 44.6M/190M [00:13<00:41, 3.46MB/s]
 24%|██▎       | 45.1M/190M [00:13<00:40, 3.55MB/s]
 24%|██▍       | 45.6M/190M [00:14<00:39, 3.66MB/s]
 24%|██▍       | 46.1M/190M [00:14<00:38, 3.77MB/s]
 25%|██▍       | 46.7M/190M [00:14<00:37, 3.81MB/s]
 25%|██▍       | 47.2M/190M [00:14<00:38, 3.69MB/s]
 25%|██▌       | 47.7M/190M [00:14<00:39, 3.58MB/s]
 25%|██▌       | 48.2M/190M [00:14<00:38, 3.71MB/s]
 26%|██▌       | 48.8M/190M [00:15<00:40, 3.45MB/s]
 26%|██▌       | 49.3M/190M [00:15<00:40, 3.45MB/s]
 26%|██▌       | 49.8M/190M [00:15<00:38, 3.66MB/s]
 27%|██▋       | 50.3M/190M [00:15<00:37, 3.73MB/s]
 27%|██▋       | 50.9M/190M [00:15<00:38, 3.60MB/s]
 27%|██▋       | 51.4M/190M [00:15<00:38, 3.56MB/s]
 27%|██▋       | 51.9M/190M [00:16<00:50, 2.73MB/s]
 28%|██▊       | 52.4M/190M [00:16<00:45, 3.01MB/s]
 28%|██▊       | 53.0M/190M [00:16<00:44, 3.09MB/s]
 28%|██▊       | 53.5M/190M [00:16<00:43, 3.13MB/s]
 28%|██▊       | 54.0M/190M [00:16<00:42, 3.21MB/s]
 29%|██▊       | 54.5M/190M [00:16<00:39, 3.39MB/s]
 29%|██▉       | 55.1M/190M [00:16<00:41, 3.24MB/s]
 29%|██▉       | 55.6M/190M [00:17<00:39, 3.40MB/s]
 30%|██▉       | 56.1M/190M [00:17<00:38, 3.49MB/s]
 30%|██▉       | 56.6M/190M [00:17<00:40, 3.32MB/s]
 30%|███       | 57.1M/190M [00:17<00:40, 3.30MB/s]
 30%|███       | 57.7M/190M [00:17<00:39, 3.37MB/s]
 31%|███       | 58.2M/190M [00:17<00:40, 3.23MB/s]
 31%|███       | 58.7M/190M [00:18<00:40, 3.24MB/s]
 31%|███       | 59.2M/190M [00:18<00:41, 3.18MB/s]
 31%|███▏      | 59.8M/190M [00:18<00:40, 3.24MB/s]
 32%|███▏      | 60.3M/190M [00:18<00:38, 3.41MB/s]
 32%|███▏      | 60.8M/190M [00:18<00:36, 3.57MB/s]
 32%|███▏      | 61.3M/190M [00:18<00:35, 3.61MB/s]
 33%|███▎      | 61.9M/190M [00:18<00:35, 3.60MB/s]
 33%|███▎      | 62.4M/190M [00:19<00:34, 3.74MB/s]
 33%|███▎      | 62.9M/190M [00:19<00:34, 3.71MB/s]
 33%|███▎      | 63.4M/190M [00:19<00:33, 3.77MB/s]
 34%|███▎      | 64.0M/190M [00:19<00:34, 3.66MB/s]
 34%|███▍      | 64.5M/190M [00:19<00:34, 3.60MB/s]
 34%|███▍      | 65.0M/190M [00:19<00:34, 3.63MB/s]
 35%|███▍      | 65.5M/190M [00:19<00:35, 3.51MB/s]
 35%|███▍      | 66.1M/190M [00:20<00:33, 3.69MB/s]
 35%|███▌      | 66.6M/190M [00:20<00:34, 3.62MB/s]
 35%|███▌      | 67.1M/190M [00:20<00:33, 3.69MB/s]
 36%|███▌      | 67.6M/190M [00:20<00:32, 3.77MB/s]
 36%|███▌      | 68.2M/190M [00:20<00:33, 3.60MB/s]
 36%|███▌      | 68.7M/190M [00:20<00:33, 3.66MB/s]
 36%|███▋      | 69.2M/190M [00:20<00:33, 3.55MB/s]
 37%|███▋      | 69.7M/190M [00:21<00:46, 2.60MB/s]
 37%|███▋      | 70.3M/190M [00:21<00:40, 2.93MB/s]
 37%|███▋      | 70.8M/190M [00:21<00:39, 3.04MB/s]
 38%|███▊      | 71.3M/190M [00:21<00:35, 3.30MB/s]
 38%|███▊      | 71.8M/190M [00:21<00:33, 3.56MB/s]
 38%|███▊      | 72.4M/190M [00:21<00:31, 3.73MB/s]
 38%|███▊      | 72.9M/190M [00:22<00:32, 3.63MB/s]
 39%|███▊      | 73.4M/190M [00:22<00:31, 3.65MB/s]
 39%|███▉      | 73.9M/190M [00:22<00:32, 3.62MB/s]
 39%|███▉      | 74.4M/190M [00:22<00:31, 3.65MB/s]
 39%|███▉      | 75.0M/190M [00:22<00:32, 3.59MB/s]
 40%|███▉      | 75.5M/190M [00:22<00:31, 3.65MB/s]
 40%|████      | 76.0M/190M [00:22<00:30, 3.70MB/s]
 40%|████      | 76.5M/190M [00:23<00:32, 3.45MB/s]
 41%|████      | 77.1M/190M [00:23<00:33, 3.39MB/s]
 41%|████      | 77.6M/190M [00:23<00:32, 3.44MB/s]
 41%|████      | 78.1M/190M [00:23<00:30, 3.63MB/s]
 41%|████▏     | 78.6M/190M [00:23<00:31, 3.57MB/s]
 42%|████▏     | 79.2M/190M [00:23<00:31, 3.50MB/s]
 42%|████▏     | 79.7M/190M [00:24<00:31, 3.46MB/s]
 42%|████▏     | 80.2M/190M [00:24<00:29, 3.69MB/s]
 43%|████▎     | 80.7M/190M [00:24<00:29, 3.74MB/s]
 43%|████▎     | 81.3M/190M [00:24<00:30, 3.53MB/s]
 43%|████▎     | 81.8M/190M [00:24<00:30, 3.51MB/s]
 43%|████▎     | 82.3M/190M [00:24<00:30, 3.52MB/s]
 44%|████▎     | 82.8M/190M [00:24<00:28, 3.72MB/s]
 44%|████▍     | 83.4M/190M [00:25<00:32, 3.29MB/s]
 44%|████▍     | 83.9M/190M [00:25<00:33, 3.19MB/s]
 44%|████▍     | 84.4M/190M [00:25<00:32, 3.26MB/s]
 45%|████▍     | 84.9M/190M [00:25<00:32, 3.21MB/s]
 45%|████▍     | 85.5M/190M [00:25<00:30, 3.43MB/s]
 45%|████▌     | 86.0M/190M [00:25<00:29, 3.52MB/s]
 46%|████▌     | 86.5M/190M [00:25<00:28, 3.62MB/s]
 46%|████▌     | 87.0M/190M [00:26<00:28, 3.64MB/s]
 46%|████▌     | 87.6M/190M [00:26<00:27, 3.67MB/s]
 46%|████▋     | 88.1M/190M [00:26<00:28, 3.56MB/s]
 47%|████▋     | 88.6M/190M [00:26<00:27, 3.72MB/s]
 47%|████▋     | 89.1M/190M [00:26<00:29, 3.46MB/s]
 47%|████▋     | 89.7M/190M [00:26<00:29, 3.36MB/s]
 47%|████▋     | 90.2M/190M [00:27<00:30, 3.29MB/s]
 48%|████▊     | 90.7M/190M [00:27<00:30, 3.20MB/s]
 48%|████▊     | 91.2M/190M [00:27<00:29, 3.38MB/s]
 48%|████▊     | 91.8M/190M [00:27<00:28, 3.40MB/s]
 49%|████▊     | 92.3M/190M [00:27<00:27, 3.60MB/s]
 49%|████▉     | 92.8M/190M [00:27<00:27, 3.59MB/s]
 49%|████▉     | 93.3M/190M [00:27<00:26, 3.65MB/s]
 49%|████▉     | 93.8M/190M [00:28<00:26, 3.68MB/s]
 50%|████▉     | 94.4M/190M [00:28<00:28, 3.30MB/s]
 50%|████▉     | 94.9M/190M [00:28<00:29, 3.23MB/s]
 50%|█████     | 95.4M/190M [00:28<00:27, 3.41MB/s]
 51%|█████     | 95.9M/190M [00:28<00:25, 3.62MB/s]
 51%|█████     | 96.5M/190M [00:28<00:27, 3.38MB/s]
 51%|█████     | 97.0M/190M [00:28<00:27, 3.39MB/s]
 51%|█████▏    | 97.5M/190M [00:29<00:26, 3.48MB/s]
 52%|█████▏    | 98.0M/190M [00:29<00:25, 3.54MB/s]
 52%|█████▏    | 98.6M/190M [00:29<00:25, 3.53MB/s]
 52%|█████▏    | 99.1M/190M [00:29<00:25, 3.60MB/s]
 52%|█████▏    | 99.6M/190M [00:29<00:24, 3.65MB/s]
 53%|█████▎    | 100M/190M [00:29<00:25, 3.53MB/s]
 53%|█████▎    | 101M/190M [00:29<00:23, 3.77MB/s]
 53%|█████▎    | 101M/190M [00:30<00:22, 3.93MB/s]
 54%|█████▎    | 102M/190M [00:30<00:23, 3.68MB/s]
 54%|█████▍    | 102M/190M [00:30<00:23, 3.70MB/s]
 54%|█████▍    | 103M/190M [00:30<00:23, 3.64MB/s]
 54%|█████▍    | 103M/190M [00:30<00:25, 3.37MB/s]
 55%|█████▍    | 104M/190M [00:30<00:24, 3.45MB/s]
 55%|█████▍    | 104M/190M [00:31<00:24, 3.50MB/s]
 55%|█████▌    | 105M/190M [00:31<00:24, 3.45MB/s]
 55%|█████▌    | 105M/190M [00:31<00:23, 3.64MB/s]
 56%|█████▌    | 106M/190M [00:31<00:23, 3.65MB/s]
 56%|█████▌    | 106M/190M [00:31<00:23, 3.60MB/s]
 56%|█████▋    | 107M/190M [00:31<00:28, 2.96MB/s]
 57%|█████▋    | 107M/190M [00:32<00:32, 2.53MB/s]
 57%|█████▋    | 108M/190M [00:32<00:30, 2.71MB/s]
 57%|█████▋    | 109M/190M [00:32<00:28, 2.90MB/s]
 57%|█████▋    | 109M/190M [00:32<00:25, 3.17MB/s]
 58%|█████▊    | 110M/190M [00:32<00:25, 3.19MB/s]
 58%|█████▊    | 110M/190M [00:32<00:23, 3.36MB/s]
 58%|█████▊    | 111M/190M [00:33<00:23, 3.33MB/s]
 59%|█████▊    | 111M/190M [00:33<00:23, 3.41MB/s]
 59%|█████▉    | 112M/190M [00:33<00:23, 3.37MB/s]
 59%|█████▉    | 112M/190M [00:33<00:22, 3.51MB/s]
 59%|█████▉    | 113M/190M [00:33<00:23, 3.22MB/s]
 60%|█████▉    | 113M/190M [00:33<00:23, 3.24MB/s]
 60%|█████▉    | 114M/190M [00:33<00:22, 3.39MB/s]
 60%|██████    | 114M/190M [00:34<00:24, 3.07MB/s]
 60%|██████    | 115M/190M [00:34<00:27, 2.68MB/s]
 61%|██████    | 115M/190M [00:34<00:26, 2.79MB/s]
 61%|██████    | 116M/190M [00:34<00:24, 3.05MB/s]
 61%|██████▏   | 116M/190M [00:34<00:24, 3.03MB/s]
 62%|██████▏   | 117M/190M [00:35<00:23, 3.08MB/s]
 62%|██████▏   | 117M/190M [00:35<00:22, 3.29MB/s]
 62%|██████▏   | 118M/190M [00:35<00:21, 3.42MB/s]
 62%|██████▏   | 118M/190M [00:35<00:21, 3.33MB/s]
 63%|██████▎   | 119M/190M [00:35<00:21, 3.23MB/s]
 63%|██████▎   | 120M/190M [00:35<00:21, 3.30MB/s]
 63%|██████▎   | 120M/190M [00:36<00:22, 3.16MB/s]
 63%|██████▎   | 121M/190M [00:36<00:21, 3.29MB/s]
 64%|██████▍   | 121M/190M [00:36<00:21, 3.22MB/s]
 64%|██████▍   | 122M/190M [00:36<00:21, 3.12MB/s]
 64%|██████▍   | 122M/190M [00:36<00:19, 3.40MB/s]
 65%|██████▍   | 123M/190M [00:36<00:23, 2.89MB/s]
 65%|██████▍   | 123M/190M [00:37<00:21, 3.12MB/s]
 65%|██████▌   | 124M/190M [00:37<00:24, 2.68MB/s]
 65%|██████▌   | 124M/190M [00:37<00:23, 2.82MB/s]
 66%|██████▌   | 125M/190M [00:37<00:21, 2.97MB/s]
 66%|██████▌   | 125M/190M [00:37<00:19, 3.23MB/s]
 66%|██████▋   | 126M/190M [00:37<00:20, 3.15MB/s]
 67%|██████▋   | 126M/190M [00:38<00:19, 3.24MB/s]
 67%|██████▋   | 127M/190M [00:38<00:18, 3.43MB/s]
 67%|██████▋   | 127M/190M [00:38<00:18, 3.44MB/s]
 67%|██████▋   | 128M/190M [00:38<00:18, 3.42MB/s]
 68%|██████▊   | 128M/190M [00:38<00:17, 3.55MB/s]
 68%|██████▊   | 129M/190M [00:38<00:16, 3.61MB/s]
 68%|██████▊   | 129M/190M [00:38<00:17, 3.50MB/s]
 68%|██████▊   | 130M/190M [00:39<00:17, 3.34MB/s]
 69%|██████▊   | 131M/190M [00:39<00:18, 3.24MB/s]
 69%|██████▉   | 131M/190M [00:39<00:17, 3.28MB/s]
 69%|██████▉   | 132M/190M [00:39<00:17, 3.32MB/s]
 70%|██████▉   | 132M/190M [00:39<00:17, 3.38MB/s]
 70%|██████▉   | 133M/190M [00:39<00:16, 3.38MB/s]
 70%|███████   | 133M/190M [00:40<00:17, 3.30MB/s]
 70%|███████   | 134M/190M [00:40<00:17, 3.23MB/s]
 71%|███████   | 134M/190M [00:40<00:19, 2.86MB/s]
 71%|███████   | 135M/190M [00:40<00:18, 3.03MB/s]
 71%|███████   | 135M/190M [00:40<00:19, 2.85MB/s]
 71%|███████▏  | 136M/190M [00:40<00:17, 3.07MB/s]
 72%|███████▏  | 136M/190M [00:41<00:16, 3.23MB/s]
 72%|███████▏  | 137M/190M [00:41<00:16, 3.23MB/s]
 72%|███████▏  | 137M/190M [00:41<00:16, 3.11MB/s]
 73%|███████▎  | 138M/190M [00:41<00:16, 3.22MB/s]
 73%|███████▎  | 138M/190M [00:41<00:17, 3.01MB/s]
 73%|███████▎  | 139M/190M [00:41<00:17, 2.98MB/s]
 73%|███████▎  | 139M/190M [00:42<00:17, 2.91MB/s]
 74%|███████▎  | 140M/190M [00:42<00:17, 2.94MB/s]
 74%|███████▍  | 141M/190M [00:42<00:19, 2.60MB/s]
 74%|███████▍  | 141M/190M [00:42<00:19, 2.50MB/s]
 75%|███████▍  | 142M/190M [00:43<00:23, 2.07MB/s]
 75%|███████▍  | 142M/190M [00:43<00:21, 2.27MB/s]
 75%|███████▌  | 143M/190M [00:43<00:18, 2.56MB/s]
 75%|███████▌  | 143M/190M [00:43<00:20, 2.33MB/s]
 76%|███████▌  | 144M/190M [00:43<00:19, 2.32MB/s]
 76%|███████▌  | 144M/190M [00:44<00:19, 2.40MB/s]
 76%|███████▌  | 145M/190M [00:44<00:17, 2.59MB/s]
 76%|███████▋  | 145M/190M [00:44<00:18, 2.44MB/s]
 77%|███████▋  | 146M/190M [00:44<00:21, 2.08MB/s]
 77%|███████▋  | 146M/190M [00:45<00:20, 2.09MB/s]
 77%|███████▋  | 147M/190M [00:45<00:18, 2.28MB/s]
 78%|███████▊  | 147M/190M [00:45<00:17, 2.39MB/s]
 78%|███████▊  | 148M/190M [00:45<00:16, 2.61MB/s]
 78%|███████▊  | 148M/190M [00:45<00:14, 2.80MB/s]
 78%|███████▊  | 149M/190M [00:46<00:14, 2.86MB/s]
 79%|███████▊  | 149M/190M [00:46<00:17, 2.32MB/s]
 79%|███████▉  | 150M/190M [00:46<00:16, 2.46MB/s]
 79%|███████▉  | 150M/190M [00:46<00:15, 2.54MB/s]
 80%|███████▉  | 151M/190M [00:46<00:13, 2.81MB/s]
 80%|███████▉  | 152M/190M [00:47<00:13, 2.85MB/s]
 80%|████████  | 152M/190M [00:47<00:11, 3.19MB/s]
 80%|████████  | 153M/190M [00:47<00:11, 3.18MB/s]
 81%|████████  | 153M/190M [00:47<00:10, 3.41MB/s]
 81%|████████  | 154M/190M [00:47<00:10, 3.36MB/s]
 81%|████████  | 154M/190M [00:47<00:10, 3.56MB/s]
 81%|████████▏ | 155M/190M [00:47<00:10, 3.46MB/s]
 82%|████████▏ | 155M/190M [00:48<00:09, 3.56MB/s]
 82%|████████▏ | 156M/190M [00:48<00:11, 3.06MB/s]
 82%|████████▏ | 156M/190M [00:48<00:11, 2.86MB/s]
 83%|████████▎ | 157M/190M [00:48<00:10, 3.15MB/s]
 83%|████████▎ | 157M/190M [00:48<00:09, 3.32MB/s]
 83%|████████▎ | 158M/190M [00:48<00:09, 3.33MB/s]
 83%|████████▎ | 158M/190M [00:49<00:08, 3.52MB/s]
 84%|████████▎ | 159M/190M [00:49<00:08, 3.66MB/s]
 84%|████████▍ | 159M/190M [00:49<00:08, 3.77MB/s]
 84%|████████▍ | 160M/190M [00:49<00:08, 3.67MB/s]
 84%|████████▍ | 160M/190M [00:49<00:07, 3.73MB/s]
 85%|████████▍ | 161M/190M [00:49<00:07, 3.85MB/s]
 85%|████████▌ | 161M/190M [00:49<00:07, 3.85MB/s]
 85%|████████▌ | 162M/190M [00:50<00:07, 3.82MB/s]
 86%|████████▌ | 163M/190M [00:50<00:07, 3.68MB/s]
 86%|████████▌ | 163M/190M [00:50<00:07, 3.51MB/s]
 86%|████████▌ | 164M/190M [00:50<00:07, 3.64MB/s]
 86%|████████▋ | 164M/190M [00:50<00:07, 3.52MB/s]
 87%|████████▋ | 165M/190M [00:50<00:07, 3.52MB/s]
 87%|████████▋ | 165M/190M [00:50<00:06, 3.58MB/s]
 87%|████████▋ | 166M/190M [00:51<00:06, 3.56MB/s]
 88%|████████▊ | 166M/190M [00:51<00:06, 3.60MB/s]
 88%|████████▊ | 167M/190M [00:51<00:06, 3.49MB/s]
 88%|████████▊ | 167M/190M [00:51<00:06, 3.60MB/s]
 88%|████████▊ | 168M/190M [00:51<00:06, 3.35MB/s]
 89%|████████▊ | 168M/190M [00:51<00:06, 3.20MB/s]
 89%|████████▉ | 169M/190M [00:51<00:06, 3.39MB/s]
 89%|████████▉ | 169M/190M [00:52<00:06, 3.26MB/s]
 89%|████████▉ | 170M/190M [00:52<00:05, 3.40MB/s]
 90%|████████▉ | 170M/190M [00:52<00:05, 3.28MB/s]
 90%|████████▉ | 171M/190M [00:52<00:05, 3.32MB/s]
 90%|█████████ | 171M/190M [00:52<00:05, 3.44MB/s]
 91%|█████████ | 172M/190M [00:52<00:04, 3.60MB/s]
 91%|█████████ | 172M/190M [00:53<00:05, 3.44MB/s]
 91%|█████████ | 173M/190M [00:53<00:04, 3.67MB/s]
 91%|█████████▏| 174M/190M [00:53<00:04, 3.57MB/s]
 92%|█████████▏| 174M/190M [00:53<00:04, 3.34MB/s]
 92%|█████████▏| 175M/190M [00:53<00:05, 2.76MB/s]
 92%|█████████▏| 175M/190M [00:53<00:04, 3.07MB/s]
 92%|█████████▏| 176M/190M [00:54<00:04, 3.17MB/s]
 93%|█████████▎| 176M/190M [00:54<00:04, 3.20MB/s]
 93%|█████████▎| 177M/190M [00:54<00:03, 3.37MB/s]
 93%|█████████▎| 177M/190M [00:54<00:03, 3.29MB/s]
 94%|█████████▎| 178M/190M [00:54<00:03, 3.53MB/s]
 94%|█████████▍| 178M/190M [00:54<00:03, 3.41MB/s]
 94%|█████████▍| 179M/190M [00:54<00:03, 3.52MB/s]
 94%|█████████▍| 179M/190M [00:55<00:02, 3.63MB/s]
 95%|█████████▍| 180M/190M [00:55<00:02, 3.56MB/s]
 95%|█████████▍| 180M/190M [00:55<00:02, 3.70MB/s]
 95%|█████████▌| 181M/190M [00:55<00:02, 3.52MB/s]
 96%|█████████▌| 181M/190M [00:55<00:02, 3.75MB/s]
 96%|█████████▌| 182M/190M [00:55<00:02, 3.50MB/s]
 96%|█████████▌| 182M/190M [00:55<00:02, 3.59MB/s]
 96%|█████████▋| 183M/190M [00:56<00:01, 3.68MB/s]
 97%|█████████▋| 184M/190M [00:56<00:01, 3.72MB/s]
 97%|█████████▋| 184M/190M [00:56<00:01, 3.74MB/s]
 97%|█████████▋| 185M/190M [00:56<00:01, 3.84MB/s]
 97%|█████████▋| 185M/190M [00:56<00:01, 3.66MB/s]
 98%|█████████▊| 186M/190M [00:56<00:01, 3.87MB/s]
 98%|█████████▊| 186M/190M [00:56<00:01, 3.79MB/s]
 98%|█████████▊| 187M/190M [00:57<00:00, 3.58MB/s]
 99%|█████████▊| 187M/190M [00:57<00:00, 3.02MB/s]
 99%|█████████▉| 188M/190M [00:57<00:00, 3.45MB/s]
 99%|█████████▉| 188M/190M [00:57<00:00, 3.20MB/s]
 99%|█████████▉| 189M/190M [00:57<00:00, 2.84MB/s]
100%|█████████▉| 189M/190M [00:58<00:00, 2.81MB/s]
100%|█████████▉| 190M/190M [00:58<00:00, 2.94MB/s]
100%|██████████| 190M/190M [00:58<00:00, 3.26MB/s]

In [4]:
#Crear el dataframe correspondiente al dataset movies_dataset.csv
movies = pd.read_csv('movies_dataset.csv')

C:\Users\ruth\AppData\Local\Temp\ipykernel_14996\3066197839.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv('movies_dataset.csv')

In [5]:
#Crear dataframe correspondiente al dataset credits.csv
credits = pd.read_csv('credits.csv')

#### Verificamos la cantidad de los registros

In [6]:
print(movies.shape, credits.shape)

(45466, 24) (45476, 3)

# Verificamos las columnas u los primeros registros de cada dataset

In [7]:
display(movies.head())

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [8]:
display(credits.head())

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

#### Verificar la informacion del tipo de valores de las columnas del dataset

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [10]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

### Transformacion de datos

Algunos campos, como belongs_to_collection, production_companies y otros, están anidados ¡deberán desanidarlos para poder y unirlos al dataset de nuevo hacer alguna de las consultas de la API! O bien buscar la manera de acceder a esos datos sin desanidarlos.

Se identificaron la siguientes columnas con datos anidados: 
belongs_to_collection, genre, production_companies, roduction_countries y spoken_languages

In [11]:
# Función para extraer y concatenar datos
def extract_concatenate_data(custom_pattern, text):
    matches = re.findall(custom_pattern, text)
    return ', '.join(matches)

# Definir los patrones de extracción
name_pattern = r"'name':\s+'(.*?)'"
director_pattern = r"'job': 'Director', 'name':\s+'(.*?)'"

# Normalizar las columnas en movies
movies['collection'] = movies['belongs_to_collection'].apply(lambda x: extract_concatenate_data(name_pattern, str(x)))
movies['genre'] = movies['genres'].apply(lambda x: extract_concatenate_data(name_pattern, str(x)))
movies['company'] = movies['production_companies'].apply(lambda x: extract_concatenate_data(name_pattern, str(x)))
movies['country'] = movies['production_countries'].apply(lambda x: extract_concatenate_data(name_pattern, str(x)))
movies['language'] = movies['spoken_languages'].apply(lambda x: extract_concatenate_data(name_pattern, str(x)))

# Normalizar la columna 'cast' en credits
credits['actor'] = credits['cast'].apply(lambda x: extract_concatenate_data(name_pattern, str(x)))

# Normalizar la columna 'crew' en credits
credits['director'] = credits['crew'].apply(lambda x: extract_concatenate_data(director_pattern, str(x)))

Desanidamos los campos `belongs_to_collection, genres, production_companies, production_countries, spoken_languages, cast y crew`

In [12]:
#Desanidar columnas 'belongs_to_collection', 'genres', 'production_companies', 'production_countries', 'spoken_languages'
columns_to_drop_movies = ['belongs_to_collection', 'genres', 'production_companies', 'production_countries', 'spoken_languages']
movies = movies.drop(columns=columns_to_drop_movies)

#Eliminar las columnas 'cast', 'crew'
columns_to_drop_credits = ['cast', 'crew']
credits = credits.drop(columns=columns_to_drop_credits)

In [13]:
display(movies.head(),credits.head())

,adult,budget,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,...,tagline,title,video,vote_average,vote_count,collection,genre,company,country,language
0,False,30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,...,NaN,Toy Story,False,7.7,5415.0,Toy Story Collection,"Animation, Comedy, Family",Pixar Animation Studios,United States of America,English
1,False,65000000,NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,...,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,,"Adventure, Fantasy, Family","TriStar Pictures, Teitler Film, Interscope Com...",United States of America,"English, Français"
2,False,0,NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,...,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection,"Romance, Comedy","Warner Bros., Lancaster Gate",United States of America,English
3,False,16000000,NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,...,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,,"Comedy, Drama, Romance",Twentieth Century Fox Film Corporation,United States of America,English
4,False,0,NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,...,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection,Comedy,"Sandollar Productions, Touchstone Pictures",United States of America,English

      id                                              actor         director
0    862  Tom Hanks, Tim Allen, Don Rickles, Jim Varney,...    John Lasseter
1   8844  Robin Williams, Jonathan Hyde, Kirsten Dunst, ...     Joe Johnston
2  15602  Walter Matthau, Jack Lemmon, Ann-Margret, Soph...    Howard Deutch
3  31357  Whitney Houston, Angela Bassett, Loretta Devin...  Forest Whitaker
4  11862  Steve Martin, Diane Keaton, Martin Short, Kimb...    Charles Shyer

Rellenar los valores nulos de las columnas 'revenue', 'budget' con el numero 0

In [14]:
movies['revenue'].fillna(0, inplace= True)
movies['budget'].fillna(0, inplace =True)

C:\Users\ruth\AppData\Local\Temp\ipykernel_14996\404767582.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['revenue'].fillna(0, inplace= True)
C:\Users\ruth\AppData\Local\Temp\ipykernel_14996\404767582.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['budget'].fillna(0, inplace =True)

Verificamos que no queden valores nulos en el dataframe

In [15]:

null_revenue = movies['revenue'].isnull().sum()
null_budget = movies['budget'].isnull().sum()

print(f"Number of null values in revenue: {null_revenue}")
print(f"Number of null values in budget: {null_budget}")

Number of null values in revenue: 0
Number of null values in budget: 0

Los valores nulos del campo release date deben eliminarse.

In [16]:
movies = movies.dropna(subset=['release_date'])

Verificar que no hayan datos nulos en la columna release_date

In [18]:

null_release_date = movies['release_date'].isnull().sum()

print(f"Number of null values in release_date: {null_release_date}")

Number of null values in release_date: 0

De haber fechas, deberán tener el formato AAAA-mm-dd, además deberán crear la columna release_year donde extraerán el año de la fecha de estreno.

In [19]:
# Convertir a datetime, coaccionando errores a NaT
movies['release_date'] = pd.to_datetime(movies['release_date'], format='%Y-%m-%d', errors='coerce')

# Crear una nueva columna 'release_year' extrayendo el año de 'release_date'
movies['release_year'] = movies['release_date'].dt.year

# Reemplazar NaN por un valor específico si es necesario, por ejemplo, 0
movies['release_year'] = movies['release_year'].fillna(0).astype(int)

# Visualizar las columnas con la fecha y el año de lanzamiento
movies[['release_date','release_year']].head()

  release_date  release_year
0   1995-10-30          1995
1   1995-12-15          1995
2   1995-12-22          1995
3   1995-12-22          1995
4   1995-02-10          1995

In [20]:
# Verificar el tipo de dato de la columna release_date y release_year

movies[['release_date','release_year']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 45379 entries, 0 to 45465
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   release_date  45376 non-null  datetime64[ns]
 1   release_year  45379 non-null  int32
dtypes: datetime64[ns](1), int32(1)
memory usage: 886.3 KB

In [21]:
# Función para verificar si un valor es estrictamente booleano
def is_strictly_boolean(value):
    return value in ['True','False']

# Filtrar registros que no son estrictamente booleanos
non_boolean_records = movies[~movies['adult'].apply(is_strictly_boolean)]

print(non_boolean_records['adult'])

19730                                   - Written by Ørnås
29503     Rune Balot goes to a casino connected to the ...
35587     Avalanche Sharks tells the story of a bikini ...
Name: adult, dtype: object

In [22]:
print(non_boolean_records.shape)

(3, 25)

In [23]:
# Filtrar y mantener solo los registros que son estrictamente booleanos
movies = movies[movies['adult'].apply(is_strictly_boolean)]

print(movies.shape)

(45376, 25)

Crear la columna con el retorno de inversión, llamada return con los campos revenue y budget, dividiendo estas dos últimas revenue / budget, cuando no hay datos disponibles para calcularlo, deberá tomar el valor 0.

In [24]:
movies.head()

,adult,budget,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,...,title,video,vote_average,vote_count,collection,genre,company,country,language,release_year
0,False,30000000,http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,...,Toy Story,False,7.7,5415.0,Toy Story Collection,"Animation, Comedy, Family",Pixar Animation Studios,United States of America,English,1995
1,False,65000000,NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,...,Jumanji,False,6.9,2413.0,,"Adventure, Fantasy, Family","TriStar Pictures, Teitler Film, Interscope Com...",United States of America,"English, Français",1995
2,False,0,NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection,"Romance, Comedy","Warner Bros., Lancaster Gate",United States of America,English,1995
3,False,16000000,NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,...,Waiting to Exhale,False,6.1,34.0,,"Comedy, Drama, Romance",Twentieth Century Fox Film Corporation,United States of America,English,1995
4,False,0,NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection,Comedy,"Sandollar Productions, Touchstone Pictures",United States of America,English,1995

In [25]:
# Asegurarse de que la columnas  budget sea de tipo float
movies['budget'] = movies['budget'].astype(float)

# Se crea la columna return 
movies['return'] = np.where(movies['budget'] != 0, (movies['revenue'] / movies['budget']).round(2), 0)

# Mostramos las columna creada
movies[['revenue','budget','return']].head()

       revenue      budget  return
0  373554033.0  30000000.0   12.45
1  262797249.0  65000000.0    4.04
2          0.0         0.0    0.00
3   81452156.0  16000000.0    5.09
4   76578911.0         0.0    0.00

Eliminar las columnas que no serán utilizadas, video,imdb_id,adult,original_title,poster_path y homepage.

In [26]:


# Lista de columnas a eliminar
columns_to_drop = ['video', 'imdb_id', 'adult', 'original_title', 'poster_path', 'homepage']

# Eliminar las columnas del DataFrame
movies = movies.drop(columns=columns_to_drop)

In [27]:

# Verificar el DataFrame resultante
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45376 entries, 0 to 45465
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             45376 non-null  float64
 1   id                 45376 non-null  object
 2   original_language  45365 non-null  object
 3   overview           44435 non-null  object
 4   popularity         45376 non-null  object
 5   release_date       45376 non-null  datetime64[ns]
 6   revenue            45376 non-null  float64
 7   runtime            45130 non-null  float64
 8   status             45296 non-null  object
 9   tagline            20398 non-null  object
 10  title              45376 non-null  object
 11  vote_average       45376 non-null  float64
 12  vote_count         45376 non-null  float64
 13  collection         45376 non-null  object
 14  genre              45376 non-null  object
 15  company            45376 non-null  object
 16  country            45376 non-null  object
 17  language           45376 non-null  object
 18  release_year       45376 non-null  int32
 19  return             45376 non-null  float64
dtypes: datetime64[ns](1), float64(6), int32(1), object(12)
memory usage: 7.1+ MB

In [28]:
# Eliminar duplicados en la columna 'id' en movies.
movies.drop_duplicates(subset='id', inplace=True)
print(movies.shape)

(45346, 20)

In [29]:
# Eliminar duplicados en la columna 'id' en credits.
credits.drop_duplicates(subset='id', inplace=True)
print(credits.shape)

(45432, 3)

### Unimos los DataFrames movies y credits

In [30]:
#cambiamos el tipo de dato en 'id' a Int 
movies['id'] = movies['id'].astype('int64')

In [37]:
# Unimos los dos DataFrames
moviesCredits = movies.merge(credits, on ='id', how = 'left')

In [38]:
print(moviesCredits.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45346 entries, 0 to 45345
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             45346 non-null  float64
 1   id                 45346 non-null  int64
 2   original_language  45335 non-null  object
 3   overview           44405 non-null  object
 4   popularity         45346 non-null  object
 5   release_date       45346 non-null  datetime64[ns]
 6   revenue            45346 non-null  float64
 7   runtime            45100 non-null  float64
 8   status             45266 non-null  object
 9   tagline            20387 non-null  object
 10  title              45346 non-null  object
 11  vote_average       45346 non-null  float64
 12  vote_count         45346 non-null  float64
 13  collection         45346 non-null  object
 14  genre              45346 non-null  object
 15  company            45346 non-null  object
 16  country            45346 non-null  object
 17  language           45346 non-null  object
 18  release_year       45346 non-null  int32
 19  return             45346 non-null  float64
 20  actor              45345 non-null  object
 21  director           45345 non-null  object
dtypes: datetime64[ns](1), float64(6), int32(1), int64(1), object(13)
memory usage: 7.4+ MB
None

In [39]:
# Seleccionar las columnas deseadas y ordenarlas
data_preparada = moviesCredits[['id', 'title', 'tagline', 'overview', 'collection', 'genre', 'company',
                               'original_language', 'runtime', 'popularity', 'vote_count', 'vote_average',
                               'release_date', 'release_year', 'status', 'country', 'language',
                               'revenue', 'budget', 'return', 'actor', 'director']]

In [40]:
# Convertir la columna 'popularity' a formato numérico
moviesCredits['popularity'] = pd.to_numeric(moviesCredits['popularity'], errors='coerce')

In [46]:
# Guardar el DataFrame como un archivo CSV
moviesCredits.to_csv('data_preparada.csv', index=False, header=True, sep=';', encoding='utf-8')

# Guardar el DataFrame como un archivo parquet
moviesCredits.to_parquet('data_preparada.parquet', index = False)

# Número de observaciones en el DataFrame
num_observaciones = len(moviesCredits)
print(f"Número de observaciones: {num_observaciones}")

Número de observaciones: 45346

In [47]:
moviesCredits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45346 entries, 0 to 45345
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             45346 non-null  float64
 1   id                 45346 non-null  int64
 2   original_language  45335 non-null  object
 3   overview           44405 non-null  object
 4   popularity         45346 non-null  float64
 5   release_date       45346 non-null  datetime64[ns]
 6   revenue            45346 non-null  float64
 7   runtime            45100 non-null  float64
 8   status             45266 non-null  object
 9   tagline            20387 non-null  object
 10  title              45346 non-null  object
 11  vote_average       45346 non-null  float64
 12  vote_count         45346 non-null  float64
 13  collection         45346 non-null  object
 14  genre              45346 non-null  object
 15  company            45346 non-null  object
 16  country            45346 non-null  object
 17  language           45346 non-null  object
 18  release_year       45346 non-null  int32
 19  return             45346 non-null  float64
 20  actor              45345 non-null  object
 21  director           45345 non-null  object
dtypes: datetime64[ns](1), float64(7), int32(1), int64(1), object(12)
memory usage: 7.4+ MB

In [49]:
data_preparada.shape

(45346, 22)